services:
  postgres:
    container_name: postgres_magermoney
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - ./db:/data/postgres
    networks:
      - postgres

  adminer:
    container_name: adminer_magermoney
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  adminer:
